// SQL Interview — 15-Level Comprehensive Roadmap
// Progressive mastery from fundamental syntax to distributed queries and mock interviews

export const SQL_INTERVIEW_ROADMAP = [
  {
    level: 1,
    title: 'SQL Fundamentals',
    emoji: '🧱',
    description: 'RDBMS concepts, tables, columns, data types, primary & foreign keys, constraints, and NULL behavior.',
    difficulty: 'Easy',
    estimatedTime: '3–5 hours',
    techStack: ['SQL', 'RDBMS', 'Keys', 'Constraints'],
    xpReward: 50,
    prerequisites: ['Basic database concepts'],
    questionIds: ['sql-q-keys-constraints', 'sql-q-null-basics'],
    locked: false
  },
  {
    level: 2,
    title: 'Query Building & Filtering',
    emoji: '🔍',
    description: 'SELECT, WHERE, DISTINCT, ORDER BY, LIMIT, OFFSET, aliases, comparison and logical operators (IN, BETWEEN, LIKE).',
    difficulty: 'Easy',
    estimatedTime: '4–6 hours',
    techStack: ['SELECT', 'WHERE', 'LIKE', 'ORDER BY'],
    xpReward: 75,
    prerequisites: ['Level 1'],
    questionIds: ['sql-q-distinct-order', 'sql-q-wildcards-like'],
    locked: false
  },
  {
    level: 3,
    title: 'Aggregation & Grouping',
    emoji: '📊',
    description: 'COUNT(*), COUNT(col), SUM, AVG, MIN, MAX, GROUP BY, and the critical difference between WHERE and HAVING.',
    difficulty: 'Easy to Medium',
    estimatedTime: '5–8 hours',
    techStack: ['GROUP BY', 'HAVING', 'Aggregations'],
    xpReward: 100,
    prerequisites: ['Level 2'],
    questionIds: ['sql-q-where-vs-having', 'sql-q-dept-avg-salary'],
    locked: false
  },
  {
    level: 4,
    title: 'Joins Masterclass',
    emoji: '🔗',
    description: 'INNER, LEFT, RIGHT, FULL OUTER, CROSS, and SELF JOINs. Multi-table joins and anti-join patterns.',
    difficulty: 'Medium',
    estimatedTime: '6–10 hours',
    techStack: ['INNER JOIN', 'LEFT JOIN', 'SELF JOIN', 'Anti-Join'],
    xpReward: 150,
    prerequisites: ['Level 3'],
    questionIds: ['sql-q-inactive-customers-join', 'sql-q-self-join-manager'],
    locked: false
  },
  {
    level: 5,
    title: 'Subqueries & EXISTS',
    emoji: '📦',
    description: 'Scalar subqueries, correlated subqueries, EXISTS vs IN, and the dangerous NOT IN + NULL trap.',
    difficulty: 'Medium',
    estimatedTime: '6–10 hours',
    techStack: ['Subqueries', 'EXISTS', 'NOT IN', 'Correlated'],
    xpReward: 150,
    prerequisites: ['Level 4'],
    questionIds: ['sql-q-above-dept-avg', 'sql-q-not-exists-null-trap'],
    locked: false
  },
  {
    level: 6,
    title: 'Advanced Transformations & CASE',
    emoji: '🔀',
    description: 'Conditional aggregation with CASE WHEN, string manipulation (CONCAT, SUBSTRING), and date functions.',
    difficulty: 'Medium',
    estimatedTime: '6–10 hours',
    techStack: ['CASE WHEN', 'Dates', 'Strings', 'COALESCE'],
    xpReward: 175,
    prerequisites: ['Level 5'],
    questionIds: ['sql-q-conditional-case-agg', 'sql-q-date-arithmetic'],
    locked: false
  },
  {
    level: 7,
    title: 'Window Functions (Foundations)',
    emoji: '🪟',
    description: 'ROW_NUMBER(), RANK(), DENSE_RANK(), NTILE(), OVER(), and PARTITION BY vs GROUP BY.',
    difficulty: 'Hard',
    estimatedTime: '8–12 hours',
    techStack: ['ROW_NUMBER', 'RANK', 'DENSE_RANK', 'OVER()'],
    xpReward: 200,
    prerequisites: ['Level 6'],
    questionIds: ['sql-q-rank-vs-dense-rank', 'sql-q-second-highest-salary'],
    locked: false
  },
  {
    level: 8,
    title: 'Common Table Expressions (CTEs)',
    emoji: '📑',
    description: 'WITH clauses, multiple CTEs, recursive queries for hierarchies, and improving query readability.',
    difficulty: 'Hard',
    estimatedTime: '6–10 hours',
    techStack: ['WITH CTE', 'Recursive CTE', 'Chained CTEs'],
    xpReward: 200,
    prerequisites: ['Level 7'],
    questionIds: ['sql-q-cte-multi-step', 'sql-q-recursive-org-chart'],
    locked: false
  },
  {
    level: 9,
    title: 'Complex Analytical Windows',
    emoji: '⚡',
    description: 'LAG(), LEAD(), FIRST_VALUE(), running totals (SUM() OVER), moving averages, and cumulative distributions.',
    difficulty: 'Hard',
    estimatedTime: '8–14 hours',
    techStack: ['LAG', 'LEAD', 'Running Total', 'Moving Average'],
    xpReward: 250,
    prerequisites: ['Level 8'],
    questionIds: ['sql-q-running-revenue', 'sql-q-month-over-month-growth'],
    locked: false
  },
  {
    level: 10,
    title: 'Gaps & Islands + Sequences',
    emoji: '🏝️',
    description: 'Detecting consecutive login streaks, repeated events, gaps in sequences, and difference-based grouping.',
    difficulty: 'Expert',
    estimatedTime: '8–14 hours',
    techStack: ['Gaps and Islands', 'Consecutive Streaks', 'Window Math'],
    xpReward: 300,
    prerequisites: ['Level 9'],
    questionIds: ['sql-q-consecutive-login-streak', 'sql-q-gaps-detection'],
    locked: false
  },
  {
    level: 11,
    title: 'Query Optimization & SARGability',
    emoji: '🚀',
    description: 'EXPLAIN plans, index seeks vs scans, B-Tree indexes, SARGable predicates, and eliminating N+1 queries.',
    difficulty: 'Expert',
    estimatedTime: '8–12 hours',
    techStack: ['EXPLAIN ANALYZE', 'Indexes', 'SARGability', 'B-Tree'],
    xpReward: 300,
    prerequisites: ['Level 10'],
    questionIds: ['sql-q-sargable-date-filter', 'sql-q-composite-index-design'],
    locked: false
  },
  {
    level: 12,
    title: 'Database Architecture & ACID',
    emoji: '🛡️',
    description: 'Transactions, isolation levels (Dirty Read, Phantom Read), Normalization (1NF to 3NF), and SQL vs NoSQL.',
    difficulty: 'Hard',
    estimatedTime: '6–10 hours',
    techStack: ['ACID', 'Isolation Levels', 'Normalization', 'Locks'],
    xpReward: 250,
    prerequisites: ['Level 11'],
    questionIds: ['sql-q-isolation-levels-anomalies', 'sql-q-normalization-design'],
    locked: false
  },
  {
    level: 13,
    title: 'Business Analytics & Cohorts',
    emoji: '📈',
    description: 'DAU/MAU, buyer retention cohorts, churn rate, conversion funnels, and customer lifetime value (LTV).',
    difficulty: 'Expert',
    estimatedTime: '10–16 hours',
    techStack: ['Retention Cohorts', 'Conversion Funnels', 'DAU/MAU'],
    xpReward: 350,
    prerequisites: ['Level 12'],
    questionIds: ['sql-q-retention-cohort-matrix', 'sql-q-conversion-funnel'],
    locked: false
  },
  {
    level: 14,
    title: 'Mock Interview Simulator',
    emoji: '🎯',
    description: 'Multi-stage interactive interview with Masti Sir: starting with basics and progressively increasing constraints.',
    difficulty: 'Expert',
    estimatedTime: '10–16 hours',
    techStack: ['Mock Interview', 'Edge Cases', 'Constraint Scaling'],
    xpReward: 400,
    prerequisites: ['Levels 1–13'],
    questionIds: ['sql-mock-nth-salary-scale', 'sql-mock-ecommerce-anomaly'],
    locked: false
  },
  {
    level: 15,
    title: 'SQL Interview Master Capstone',
    emoji: '🏆',
    description: 'Analyze a complete multi-table E-Commerce enterprise database with 50+ real-world analytical problems.',
    difficulty: 'Capstone',
    estimatedTime: '16–24 hours',
    techStack: ['Full Enterprise Schema', 'All SQL Disciplines'],
    xpReward: 1000,
    prerequisites: ['Levels 1–14'],
    questionIds: ['sql-cap-ecommerce-audit', 'sql-cap-revenue-attribution'],
    locked: false
  }
]
